{
  "openapi" : "3.0.0",
  "servers" : [ {
    "description" : "",
    "url" : "https://csaba98apis.onrender.com"
  } ],
  "info" : {
    "description" : "A simple API to manage customers data with in-memory database.\r\n\r\nUsername: test\r\n\r\nPassword: Abcd1234*-",
    "version" : "1.0.0",
    "title" : "Customers API",
    "contact" : {
      "email" : "csabavasteleki@hotmail.hu"
    },
    "license" : {
      "name" : "",
      "url" : ""
    }
  },
  "tags" : [ {
    "name" : "customer"
  }, {
    "name" : "customers"
  } ],
  "paths" : {
    "/api/customer" : {
      "parameters" : [ ],
      "post" : {
        "summary" : "Create a new customer",
        "tags" : [ "customer" ],
        "responses" : {
          "201" : {
            "description" : "Created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Customer"
                },
                "examples" : {
                  "Example 1" : {
                    "value" : {
                      "id" : 1,
                      "firstname" : "Jakab",
                      "lastname" : "Gipsz",
                      "phone" : "+36201234567",
                      "email" : "tstemail@email.com",
                      "username" : "jakab.gipsz",
                      "password" : "EncodedPw",
                      "age" : 20
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "get-api-customer",
        "requestBody" : {
          "$ref" : "#/components/requestBodies/addCustomer"
        }
      },
      "put" : {
        "summary" : "Update existing customer",
        "tags" : [ "customer" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Customer"
                },
                "examples" : {
                  "Example 1" : {
                    "value" : {
                      "id" : 1,
                      "firstname" : "Jakab",
                      "lastname" : "Gipsz",
                      "phone" : "+36201234567",
                      "email" : "tstemail@email.com",
                      "username" : "jakab.gipsz",
                      "password" : "DecodedPw",
                      "age" : 20
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "put-api-customer",
        "description" : "",
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateCustomer"
        }
      }
    },
    "/api/customers/count" : {
      "get" : {
        "summary" : "Get customers count",
        "tags" : [ "customers" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "count" : {
                      "type" : "number",
                      "x-stoplight" : {
                        "id" : "r0dm048ikagcb"
                      }
                    }
                  }
                },
                "examples" : {
                  "Example 1" : {
                    "value" : {
                      "count" : 100
                    }
                  }
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "get-api-customers-count"
      }
    },
    "/api/customers/avgage" : {
      "get" : {
        "summary" : "Get customers average age",
        "tags" : [ "customers" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "avgage" : {
                      "type" : "number",
                      "x-stoplight" : {
                        "id" : "c7au3d694xjtd"
                      }
                    }
                  }
                },
                "examples" : {
                  "Example 1" : {
                    "value" : {
                      "avgage" : 20
                    }
                  }
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "get-api-customers-avgage"
      }
    },
    "/api/customers/filterbyage" : {
      "get" : {
        "summary" : "Get customers filter by age between minAge and maxAge",
        "tags" : [ "customers" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Customers"
                },
                "examples" : {
                  "Example 1" : {
                    "value" : [ {
                      "id" : 1,
                      "firstname" : "Jakab",
                      "lastname" : "Gipsz",
                      "phone" : "+36201234567",
                      "email" : "tstemail@email.com",
                      "username" : "jakab.gipsz",
                      "password" : "TstPwd1234*-",
                      "age" : 20
                    } ]
                  }
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "get-api-customers-filterbyage",
        "parameters" : [ {
          "schema" : {
            "type" : "string",
            "example" : "10"
          },
          "in" : "query",
          "name" : "minAge",
          "required" : true
        }, {
          "schema" : {
            "type" : "string",
            "example" : "60"
          },
          "in" : "query",
          "name" : "maxAge",
          "required" : true
        } ]
      }
    },
    "/api/customers/{id}" : {
      "get" : {
        "summary" : "Get customer data",
        "tags" : [ "customers" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Customer"
                },
                "examples" : {
                  "Example 1" : {
                    "value" : {
                      "id" : 1,
                      "firstname" : "Jakab",
                      "lastname" : "Gipsz",
                      "phone" : "+36201234567",
                      "email" : "tstemail@email.com",
                      "username" : "jakab.gipsz",
                      "password" : "TstPwd1234*-",
                      "age" : 20
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "get-api-customers-id",
        "parameters" : [ ]
      },
      "parameters" : [ {
        "schema" : {
          "type" : "string",
          "example" : "1"
        },
        "name" : "id",
        "in" : "path",
        "required" : true
      } ],
      "delete" : {
        "summary" : "Delete customer",
        "tags" : [ "customers" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "text/html" : {
                "schema" : {
                  "type" : "string",
                  "default" : "Customer deleted successfully!"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "delete-api-customers-id",
        "parameters" : [ ]
      }
    },
    "/api/customers" : {
      "get" : {
        "summary" : "Get all customers",
        "tags" : [ "customers" ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "get-api-customers",
        "parameters" : [ ]
      },
      "post" : {
        "summary" : "Create new customers",
        "tags" : [ "customers" ],
        "responses" : {
          "201" : {
            "description" : "Created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Customers"
                },
                "examples" : {
                  "Example 1" : {
                    "value" : [ {
                      "id" : 1,
                      "firstname" : "Jakab",
                      "lastname" : "Gipsz",
                      "phone" : "+36201234567",
                      "email" : "tstemail@email.com",
                      "username" : "jakab.gipsz",
                      "password" : "DecodedPw",
                      "age" : 20
                    }, {
                      "id" : 2,
                      "firstname" : "Marcell",
                      "lastname" : "Horv√°th",
                      "phone" : "+36201234567",
                      "email" : "tstemail@email.com",
                      "username" : "marcell.horvath",
                      "password" : "DecodedPw",
                      "age" : 30
                    } ]
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "post-api-customers",
        "requestBody" : {
          "$ref" : "#/components/requestBodies/addCustomers"
        }
      },
      "put" : {
        "summary" : "Update existing customers",
        "tags" : [ "customers" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Customers"
                },
                "examples" : {
                  "Example 1" : {
                    "value" : [ {
                      "id" : 1,
                      "firstname" : "Jakab",
                      "lastname" : "Gipsz",
                      "phone" : "+36201234567",
                      "email" : "tstemail@email.com",
                      "username" : "jakab.gipsz",
                      "password" : "DecodedPw",
                      "age" : 20
                    }, {
                      "id" : 2,
                      "firstname" : "Marcell",
                      "lastname" : "Horv√°th",
                      "phone" : "+36201234567",
                      "email" : "tstemail@email.com",
                      "username" : "marcell.horvath",
                      "password" : "DecodedPw",
                      "age" : 30
                    } ]
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "put-api-customers",
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateCustomers"
        },
        "parameters" : [ ]
      },
      "delete" : {
        "summary" : "Delete all customers",
        "tags" : [ "customers" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "text/html" : {
                "schema" : {
                  "type" : "string",
                  "default" : "Customers deleted successfully!"
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized"
          }
        },
        "operationId" : "delete-api-customers"
      },
      "parameters" : [ ]
    }
  },
  "components" : {
    "schemas" : {
      "Customer" : {
        "title" : "Customer",
        "type" : "object",
        "x-examples" : {
          "Example 1" : [ {
            "id" : 1,
            "firstname" : "Jakab",
            "lastname" : "Gipsz",
            "phone" : "+36201234567",
            "email" : "tstemail@email.com",
            "username" : "jakab.gipsz",
            "password" : "TstPwd1234*-",
            "age" : 20
          } ]
        },
        "properties" : {
          "id" : {
            "type" : "number"
          },
          "firstname" : {
            "type" : "string",
            "x-stoplight" : {
              "id" : "vhaq2jcxy4snq"
            }
          },
          "lastname" : {
            "type" : "string",
            "x-stoplight" : {
              "id" : "9e4jq9vi1idnn"
            }
          },
          "phone" : {
            "type" : "string",
            "x-stoplight" : {
              "id" : "ktca5fgs5jwkw"
            },
            "pattern" : "[\\\\+](36)(20|30|31|50|70)\\\\d{7}"
          },
          "email" : {
            "type" : "string",
            "x-stoplight" : {
              "id" : "db9ucm02qnfpv"
            }
          },
          "username" : {
            "type" : "string",
            "x-stoplight" : {
              "id" : "1i10xfrjsgpn5"
            }
          },
          "password" : {
            "type" : "string",
            "x-stoplight" : {
              "id" : "hyai6wqrqomqs"
            }
          },
          "age" : {
            "type" : "integer",
            "x-stoplight" : {
              "id" : "gqsmd48b0uwcz"
            }
          }
        }
      },
      "Customers" : {
        "title" : "Customers",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/Customer"
        },
        "x-examples" : {
          "Example 1" : [ {
            "id" : 1,
            "firstname" : "Jakab",
            "lastname" : "Gipsz",
            "phone" : "+36201234567",
            "email" : "tstemail@email.com",
            "username" : "jakab.gipsz",
            "password" : "TstPwd1234*-"
          }, {
            "id" : 2,
            "firstname" : "Marcell",
            "lastname" : "Horv√°th",
            "phone" : "+36201234567",
            "email" : "tstemail@email.com",
            "username" : "marcell.horvath",
            "password" : "TstPwd1234*-"
          } ]
        }
      }
    },
    "securitySchemes" : {
      "BasicAuth" : {
        "type" : "http",
        "scheme" : "basic"
      }
    },
    "examples" : { },
    "parameters" : { },
    "responses" : { },
    "requestBodies" : {
      "addCustomer" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Customer"
            },
            "examples" : {
              "Example 1" : {
                "value" : {
                  "firstname" : "Jakab",
                  "lastname" : "Gipsz",
                  "phone" : "+36201234567",
                  "email" : "tstemail@email.com",
                  "username" : "jakab.gipsz",
                  "password" : "TstPwd1234*-",
                  "age" : 20
                }
              }
            }
          }
        }
      },
      "addCustomers" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Customers"
            },
            "examples" : {
              "Example 1" : {
                "value" : [ {
                  "firstname" : "Jakab",
                  "lastname" : "Gipsz",
                  "phone" : "+36201234567",
                  "email" : "tstemail@email.com",
                  "username" : "jakab.gipsz",
                  "password" : "TstPwd1234*-",
                  "age" : 20
                }, {
                  "firstname" : "Marcell",
                  "lastname" : "Horv√°th",
                  "phone" : "+36201234567",
                  "email" : "tstemail@email.com",
                  "username" : "marcell.horvath",
                  "password" : "TstPwd1234*-",
                  "age" : 30
                } ]
              }
            }
          }
        }
      },
      "updateCustomer" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Customer"
            },
            "examples" : {
              "Example 1" : {
                "value" : {
                  "id" : 1,
                  "firstname" : "Jakab",
                  "lastname" : "Gipsz",
                  "phone" : "+36201234567",
                  "email" : "tstemail@email.com",
                  "username" : "jakab.gipsz",
                  "password" : "TstPwd1234*-",
                  "age" : 20
                }
              }
            }
          }
        }
      },
      "updateCustomers" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Customers"
            },
            "examples" : {
              "Example 1" : {
                "value" : [ {
                  "id" : 1,
                  "firstname" : "Jakab",
                  "lastname" : "Gipsz",
                  "phone" : "+36201234567",
                  "email" : "tstemail@email.com",
                  "username" : "jakab.gipsz",
                  "password" : "TstPwd1234*-",
                  "age" : 20
                }, {
                  "id" : 2,
                  "firstname" : "Marcell",
                  "lastname" : "Horv√°th",
                  "phone" : "+36201234567",
                  "email" : "tstemail@email.com",
                  "username" : "marcell.horvath",
                  "password" : "TstPwd1234*-",
                  "age" : 30
                } ]
              }
            }
          }
        }
      }
    }
  },
  "security" : [ {
    "BasicAuth" : [ ]
  } ]
}